### ISSUE TITLE
Open dropdown filter when click on table header 

### ISSUE THREAD

**Issue by DarrMirr** [chestercharles/excel-bootstrap-table-filter#22]
Hello!

Users try to click on table header (on text) in order to open dropdown filter. But they have to click on arrow icon which places near table header. How can I make the same operation by clicking on table header (on text)?

with regards
Darr Mirr

**Comment by chestercharles** [comment]
Hi Darr,

Each `FilterMenu` is generated and inserted into its respective `th` element looking something like this:
```
<th class="filter">
  Animal
  <div class="dropdown-filter-dropdown">
    <span class="glyphicon glyphicon-arrow-down dropdown-filter-icon">
      <i class="arrow-down"></i>
    </span>
    <div class="dropdown-filter-content">
      ...
    </div>
  </div>
</th>
```

The trigger for the click handler [is defined in FilterMenu.ts](https://github.com/chestercharles/excel-bootstrap-table-filter/blob/master/src/FilterMenu.ts#L27):

```
// FilterMenu.ts

// variables for click handlers
let $trigger = $(this.menu.children[0]);
...
// toggle hide/show when the trigger is clicked
$trigger.click(() => $content.toggle());
```

In the line of TS above, `this.menu` refers to the `div.dropdown-filter-dropdown` element, which means that the click handler is bound to the first child element (`span.glyphicon.glyphicon-arrow-down.dropdown-filter-icon `).

If you want the filter content to be toggled when the user clicks on the word ("Animal" in this case), you would need to change line 27 in `FilterMenu.ts` to grab the parent of `this.menu`, instead of the first child.

I haven't tried this, so I don;t know if this change would cause bugs elsewhere.

In any case, if you make the change, you will also need to recompile the module to get the output JS file. You will have to clone the whole project, make the changes, and then run the `npm build` script.

**Comment by DarrMirr** [comment]
Hi chestercharles,

Thanks for quick response.

I tried to make parent element as trigger. It works. But there is some issues: 

- filter is closed immediately when I click on table header due to `!$menu.is(el.target) && $menu.has(el.target).length === 0` condition
- filter is hidden when I click on checkbox

I find out some workaround to resolve this issue.

Thank you for help me
