### ISSUE TITLE
Performance issue when records are too many

### ISSUE THREAD

**Issue by ujvala-bhumi** [chestercharles/excel-bootstrap-table-filter#24]
This is regarding performance. I am trying to load heavy data with 5000+ records. When i am doing select/de-select operations, page is going unresponsive. Please look into this.

**Comment by chestercharles** [comment]
If you are dealing with large amounts of data, you probably want to be using pagination, which this plugin does not support.

I would suggest using something like [datatables](https://datatables.net).

**Comment by ujvala-bhumi** [comment]
Datatables is  a heavy library to use, hence i wanted to check if this supports. Anyways leveraged datatables' feature to implement pagination.  Thanks

**Comment by giuliohome** [comment]
Same issue here. I've chosen this because of the excel flavor filters. I can't find such a thing in datatables, there they search a string among all columns, that makes no sense in my scenario. I would be glad to help: is pagination so difficult to implement? Just to know, why doesn't this plugin support it? If you can clarify the reason, so that I can also make an informed decision: spend my time for a pagination enhancement here or try to reimplement this single column filters in another library like datatables. Thank you

**Comment by giuliohome** [comment]
Never mind! Found a [plugin of datatables](https://datatables.net/examples/api/multi_filter_select.html) that is doing exactly this job! Will convert my project to datatables!
